# -*- coding: utf-8 -*-
"""exercicio_dois

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/147vk1NZk6R7EbTRzy5vDcIwQqDa-1bXI
"""

numeros_inteiros = []

print("Digite 10 números inteiros para preencher a estrutura de dados.")
print("-----------------------------------------------------------------------------")

for i in range(10):
    while True:
        try:
            numero = int(input(f"Digite o {i+1}º número: "))
            numeros_inteiros.append(numero)
            break
        except ValueError:1

print("Números digitados:", numeros_inteiros)
print("\n-----------------------------------------------------------------------------")

novo_numero = int(input("\nDigite um novo número inteiro: "))

if novo_numero in numeros_inteiros:
    posicoes = [i for i, n in enumerate(numeros_inteiros) if n == novo_numero]
    print(f"O número {novo_numero} foi encontrado nas posições: {posicoes}")
else:
    print(f"O número {novo_numero} não foi encontrado na lista.")

