# -*- coding: utf-8 -*-
"""exercicio_quatro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H1YzbDlZoRJXJn_OZe8hIbqmimTLrGue
"""

# Solicita os números sorteados
print("Digite os 6 números sorteados na Mega-Sena:")
sorteados = []
for i in range(6):
    numero = int(input(f"Digite o {i+1}º número sorteado: "))
    sorteados.append(numero)

# Solicita os números do jogador
print("\nDigite os 6 números do seu jogo:")
jogo = []
for i in range(6):
    numero = int(input(f"Digite o {i+1}º número do seu jogo: "))
    jogo.append(numero)

# Conta quantos números o jogador acertou
acertos = 0
for numero in jogo:
    if numero in sorteados:
        acertos += 1

# Mostra o resultado
print("\nNúmeros sorteados:", sorteados)
print("Seus números:", jogo)
print(f"Você acertou {acertos} número(s)!")